config/routes.rb
Rails.application.routes.draw do
	root 'about#welcome'
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :posts do
  	collection do
  		get :all, action: :index, defaults: { all: true }
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def welcome
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		if params[:all] == true
			@posts = Post.all
		else
			@posts = current_user.posts
		end
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:content)
	end

	def set_post
		@post = Post.find(params[:id])
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/welcome.html.erb
<div class="btn btn-primary">dfasdsfa</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "로그인", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :content %>
	<%= f.text_field :content %>
	<%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<%= link_to "내 글 보기", posts_path %>
<%= link_to "전체 글 보기", all_posts_path %>
<%= link_to "새 글 작성하기", new_post_path %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>작성자</th>
			<th>요약</th>
			<th>자세히보기</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
				<tr>
						<td><%= post.user.name %></td>
						<td><%= post.content[0..100] %></td>
						<td><%= link_to "자세히 보기", post %></td>
				</tr>
		<% end %>
	</tbody>
</table>

app/views/posts/new.html.erb
<h3>새 글 작성하기</h3>
<%= render 'posts/form' %>
<%= link_to "돌아가기", posts_path, class: "btn btn-default" %>

app/views/posts/show.html.erb
<h3>글 보기</h3>
<h5>작성자: <%= @post.user.name %></h5>
<p><%= @post.content %></p>
<%= link_to "목록", posts_path %>